application: neperczagtu
version: 5
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  script: main.py

- url: /post/twitter
  script: twitter.py
  login: admin

- url: /new
  script: new.py

- url: /edit
  script: edit.py
  
- url: /login/(twitter|facebook|draugiem)
  script: login.py

- url: /confirm
  script: confirm.py

- url: /img_(.*)-(.*)\.png
  script: img.py

- url: /more\.html
  script: more.py

- url: /info/(\d+)
  script: info.py

- url: /static
  static_dir: static

- url: /.*
  static_files: static/404.html
  upload: static/404.html
