application: neperczagtu-test
version: 5
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.template$
- ^dumps$

derived_file_type:
- python_precompiled

error_handlers:
  - file: views/500.html

admin_console:
  pages:
  - name: Posts
    url: /admin/posts

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /cron/cleanup_auth_tokens
  script: cron.py
  login: admin
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  script: main.py

- url: /post/twitter
  script: twitter.py
  login: admin

- url: /new
  script: new.py

- url: /edit
  script: edit.py
  
- url: /login/(twitter|facebook|draugiem)
  script: login.py

- url: /confirm
  script: confirm.py

- url: /img_(.*)-(.*)\.png
  script: img.py

- url: /more\.html
  script: more.py

- url: /info/(\d+)
  script: info.py

- url: /static
  static_dir: static

- url: /admin/cleanup
  script: cleanup.py
  login: admin

- url: /admin/posts
  script: admin.py
  login: admin

- url: /admin/posts/(\d+)/(delete|edit|confirm)
  script: admin.py
  login: admin

- url: /.*
  static_files: static/404.html
  upload: static/404.html
